# Generated by Django 5.1.5 on 2025-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.FloatField(verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('approval_note', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('total_days', models.FloatField(default=0, verbose_name='总天数')),
                ('used_days', models.FloatField(default=0, verbose_name='已用天数')),
                ('remaining_days', models.FloatField(default=0, verbose_name='剩余天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '请假余额',
                'verbose_name_plural': '请假余额',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='请假类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('max_days_per_year', models.IntegerField(default=0, verbose_name='每年最大天数')),
                ('is_paid', models.BooleanField(default=True, verbose_name='是否带薪')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '请假类型',
                'verbose_name_plural': '请假类型',
            },
        ),
    ]
