# Generated by Django 5.1.5 on 2025-05-25 06:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=users.models.get_current_date, verbose_name='入职日期'),
        ),
    ]
