# Generated by Django 5.1.5 on 2025-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=50, verbose_name='教育程度'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, verbose_name='专业技能'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='工作经验'),
        ),
    ]
