# Generated by Django 5.1.5 on 2025-07-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_education_user_major_user_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.TextField(blank=True, null=True, verbose_name='人脸特征编码'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/', verbose_name='人脸图片'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_registered',
            field=models.BooleanField(default=False, verbose_name='是否已录入人脸'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='人脸录入时间'),
        ),
    ]
