# Generated by Django 5.1.5 on 2026-01-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_face_encoding_user_face_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
    ]
