# Generated by Django 5.1.5 on 2025-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_evaluation_score', models.FloatField(blank=True, null=True, verbose_name='自评分数')),
                ('self_evaluation_comment', models.TextField(blank=True, verbose_name='自评意见')),
                ('self_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='自评时间')),
                ('manager_evaluation_score', models.FloatField(blank=True, null=True, verbose_name='上级评分')),
                ('manager_evaluation_comment', models.TextField(blank=True, verbose_name='上级评估意见')),
                ('manager_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='上级评估时间')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='最终得分')),
                ('final_rating', models.CharField(blank=True, choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般'), ('poor', '差')], max_length=10, null=True, verbose_name='最终等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('self_evaluated', '自评完成'), ('manager_evaluated', '上级评估完成'), ('finalized', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '绩效评估',
                'verbose_name_plural': '绩效评估',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_score', models.FloatField(blank=True, null=True, verbose_name='自评分数')),
                ('self_comment', models.TextField(blank=True, verbose_name='自评说明')),
                ('manager_score', models.FloatField(blank=True, null=True, verbose_name='上级评分')),
                ('manager_comment', models.TextField(blank=True, verbose_name='上级评价')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='最终分数')),
            ],
            options={
                'verbose_name': '绩效评估明细',
                'verbose_name_plural': '绩效评估明细',
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝')], default='draft', max_length=10, verbose_name='状态')),
                ('approval_note', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '绩效目标',
                'verbose_name_plural': '绩效目标',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.TextField(verbose_name='目标值')),
                ('weight', models.FloatField(verbose_name='权重(%)')),
            ],
            options={
                'verbose_name': '绩效目标明细',
                'verbose_name_plural': '绩效目标明细',
            },
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('description', models.TextField(blank=True, verbose_name='指标描述')),
                ('weight', models.FloatField(verbose_name='权重(%)')),
                ('max_score', models.IntegerField(default=100, verbose_name='满分')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '绩效指标',
                'verbose_name_plural': '绩效指标',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='周期名称')),
                ('period_type', models.CharField(choices=[('monthly', '月度'), ('quarterly', '季度'), ('yearly', '年度')], max_length=10, verbose_name='周期类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '绩效考核周期',
                'verbose_name_plural': '绩效考核周期',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '绩效模板',
                'verbose_name_plural': '绩效模板',
            },
        ),
    ]
