# Generated by Django 5.1.5 on 2025-05-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评估人'),
        ),
        migrations.AddField(
            model_name='performanceevaluationdetail',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='performance.performanceevaluation', verbose_name='绩效评估'),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goals', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='performance.performancegoal', verbose_name='绩效目标'),
        ),
        migrations.AddField(
            model_name='performancegoaldetail',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='performance.performancegoal', verbose_name='绩效目标'),
        ),
        migrations.AddField(
            model_name='performancegoaldetail',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performanceindicator', verbose_name='绩效指标'),
        ),
        migrations.AddField(
            model_name='performanceevaluationdetail',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performanceindicator', verbose_name='绩效指标'),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performanceperiod', verbose_name='考核周期'),
        ),
        migrations.AddField(
            model_name='performanceindicator',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='performance.performancetemplate', verbose_name='绩效模板'),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performancetemplate', verbose_name='绩效模板'),
        ),
        migrations.AlterUniqueTogether(
            name='performancegoal',
            unique_together={('user', 'period')},
        ),
    ]
