# Generated by Django 5.1.5 on 2025-05-25 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(choices=[('employee', '人事报表'), ('attendance', '考勤报表'), ('salary', '薪资报表'), ('performance', '绩效报表'), ('custom', '自定义报表')], max_length=50, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报表分类',
                'verbose_name_plural': '报表分类',
                'db_table': 'report_category',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='模板代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('query_sql', models.TextField(blank=True, verbose_name='查询SQL')),
                ('template_config', models.JSONField(default=dict, verbose_name='模板配置')),
                ('default_format', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='xlsx', max_length=10, verbose_name='默认格式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportcategory', verbose_name='分类')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'db_table': 'report_template',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '每季度'), ('yearly', '每年')], max_length=20, verbose_name='频率')),
                ('schedule_time', models.TimeField(verbose_name='执行时间')),
                ('parameters', models.JSONField(default=dict, verbose_name='参数')),
                ('formats', models.JSONField(default=list, verbose_name='输出格式')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('email_recipients', models.TextField(blank=True, verbose_name='收件人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '定时报表任务',
                'verbose_name_plural': '定时报表任务',
                'db_table': 'report_schedule',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('parameters', models.JSONField(default=dict, verbose_name='报表参数')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_format', models.CharField(max_length=10, verbose_name='文件格式')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '报表',
                'verbose_name_plural': '报表',
                'db_table': 'report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], max_length=20, verbose_name='级别')),
                ('module', models.CharField(choices=[('users', '用户管理'), ('attendance', '考勤管理'), ('salary', '薪资管理'), ('performance', '绩效管理'), ('leave', '请假管理'), ('reports', '报表管理'), ('system', '系统')], max_length=50, verbose_name='模块')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('message', models.CharField(max_length=500, verbose_name='消息')),
                ('full_message', models.TextField(blank=True, verbose_name='完整消息')),
                ('stack_trace', models.TextField(blank=True, verbose_name='堆栈信息')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='会话ID')),
                ('request_id', models.CharField(blank=True, max_length=100, verbose_name='请求ID')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='文件名')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='行号')),
                ('function_name', models.CharField(blank=True, max_length=100, verbose_name='函数名')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='system_log_timesta_2209e3_idx'), models.Index(fields=['level'], name='system_log_level_48c2a6_idx'), models.Index(fields=['module'], name='system_log_module_e8c164_idx'), models.Index(fields=['user'], name='system_log_user_id_fcedc2_idx')],
            },
        ),
    ]
