# Generated by Django 5.1.5 on 2025-05-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='salary_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='salary.salaryrecord', verbose_name='工资记录'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salarystructure', verbose_name='薪酬结构'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('user', 'year', 'month')},
        ),
    ]
