# Generated by Django 5.1.5 on 2026-01-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='财务批准时间'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='finance_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salaries', to=settings.AUTH_USER_MODEL, verbose_name='财务批准人'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='finance_note',
            field=models.TextField(blank=True, verbose_name='财务批准意见'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_salaries', to=settings.AUTH_USER_MODEL, verbose_name='审核经理'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='manager_note',
            field=models.TextField(blank=True, verbose_name='经理审核意见'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='经理审核时间'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_salaries', to=settings.AUTH_USER_MODEL, verbose_name='发放人'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_salaries', to=settings.AUTH_USER_MODEL, verbose_name='拒绝人'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='拒绝原因'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('manager_reviewed', '经理已审核'), ('finance_approved', '财务已批准'), ('paid', '已发放'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
