# Generated by Django 5.1.5 on 2026-01-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
        ('salary', '0003_salaryrecord_finance_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('full_attendance_bonus', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='全勤奖金额')),
                ('performance_level_a_min', models.FloatField(default=90, verbose_name='A级最低分')),
                ('performance_level_b_min', models.FloatField(default=80, verbose_name='B级最低分')),
                ('performance_level_c_min', models.FloatField(default=60, verbose_name='C级最低分')),
                ('performance_level_a_coefficient', models.FloatField(default=1.5, verbose_name='A级绩效系数')),
                ('performance_level_b_coefficient', models.FloatField(default=1.2, verbose_name='B级绩效系数')),
                ('performance_level_c_coefficient', models.FloatField(default=1.0, verbose_name='C级绩效系数')),
                ('performance_level_d_coefficient', models.FloatField(default=0.5, verbose_name='D级绩效系数')),
                ('performance_bonus_base_rate', models.FloatField(default=0.2, verbose_name='绩效奖金基数比例')),
                ('sick_leave_free_days', models.IntegerField(default=2, verbose_name='病假免扣天数')),
                ('sick_leave_deduction_rate', models.FloatField(default=0.5, verbose_name='病假扣款比例')),
                ('personal_leave_deduction_rate', models.FloatField(default=1.0, verbose_name='事假扣款比例')),
                ('late_deduction_minor', models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='轻微迟到扣款')),
                ('late_deduction_major', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='严重迟到扣款')),
                ('late_threshold_minutes', models.IntegerField(default=30, verbose_name='迟到严重阈值(分钟)')),
                ('absence_deduction_rate', models.FloatField(default=1.0, verbose_name='缺勤扣款比例(按日薪)')),
                ('work_days_per_month', models.IntegerField(default=22, verbose_name='每月工作日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '薪资计算配置',
                'verbose_name_plural': '薪资计算配置',
            },
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='absence_count',
            field=models.IntegerField(default=0, verbose_name='缺勤次数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='缺勤扣款'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='actual_work_days',
            field=models.IntegerField(default=0, verbose_name='实际出勤天数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='early_leave_count',
            field=models.IntegerField(default=0, verbose_name='早退次数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='full_attendance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='全勤奖'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='is_full_attendance',
            field=models.BooleanField(default=False, verbose_name='是否全勤'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='late_count',
            field=models.IntegerField(default=0, verbose_name='迟到次数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='迟到扣款'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='leave_days',
            field=models.FloatField(default=0, verbose_name='当月请假天数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='请假扣款'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='other_leave_days',
            field=models.FloatField(default=0, verbose_name='其他假期天数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='performance_coefficient',
            field=models.FloatField(default=1.0, verbose_name='绩效系数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='performance_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.performanceevaluation', verbose_name='绩效评估'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='performance_level',
            field=models.CharField(blank=True, choices=[('A', '优秀'), ('B', '良好'), ('C', '合格'), ('D', '待改进')], max_length=1, null=True, verbose_name='绩效等级'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='performance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='绩效得分'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='personal_leave_days',
            field=models.FloatField(default=0, verbose_name='事假天数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='sick_leave_days',
            field=models.FloatField(default=0, verbose_name='病假天数'),
        ),
    ]
