# Generated by Django 5.1.5 on 2026-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salaryconfig_salaryrecord_absence_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='overtime_holiday_rate',
            field=models.FloatField(default=2.0, verbose_name='节假日加班系数'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='overtime_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='加班时薪(元/小时)'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='overtime_weekend_rate',
            field=models.FloatField(default=1.5, verbose_name='周末加班系数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='overtime_count',
            field=models.IntegerField(default=0, verbose_name='加班次数'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='overtime_hours',
            field=models.FloatField(default=0, verbose_name='加班小时数'),
        ),
    ]
