# Generated by Django 5.1.5 on 2026-01-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_salaryconfig_overtime_holiday_rate_and_more'),
    ]

    operations = [
    ]
