# Generated by Django 5.1.5 on 2025-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('late', '迟到申请'), ('early', '早退申请'), ('absent', '缺勤申请'), ('overtime', '加班申请')], max_length=10, verbose_name='异常类型')),
                ('exception_date', models.DateField(verbose_name='异常日期')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审批状态')),
                ('approval_note', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考勤异常申请',
                'verbose_name_plural': '考勤异常申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_time', models.DateTimeField(verbose_name='打卡时间')),
                ('clock_type', models.CharField(choices=[('in', '上班打卡'), ('out', '下班打卡')], max_length=3, verbose_name='打卡类型')),
                ('status', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early', '早退'), ('absent', '缺勤')], default='normal', max_length=10, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='打卡位置')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_images/', verbose_name='人脸照片')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-clock_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班次名称')),
                ('weekday', models.IntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='上班时间')),
                ('end_time', models.TimeField(verbose_name='下班时间')),
                ('late_threshold', models.IntegerField(default=10, verbose_name='迟到阈值(分钟)')),
                ('early_threshold', models.IntegerField(default=10, verbose_name='早退阈值(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作时间表',
                'verbose_name_plural': '工作时间表',
            },
        ),
    ]
