# Generated by Django 5.1.5 on 2026-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_workschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceexception',
            name='overtime_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='加班结束时间'),
        ),
        migrations.AddField(
            model_name='attendanceexception',
            name='overtime_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='加班时长(小时)'),
        ),
        migrations.AddField(
            model_name='attendanceexception',
            name='overtime_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='加班开始时间'),
        ),
    ]
