# Generated by Django 5.1.5 on 2026-01-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendanceexception_overtime_end_time_and_more'),
    ]

    operations = [
    ]
